name: 'CORS Check'
description: 'Ping given URL (with curl) for a CORS check. With redirect and retrying capabilities'
author: 'Qiming-Liu'
inputs:
  url:
    description: Target URL(s), split by |
    required: true
  method:
    description: HTTP method to use
    required: false
    default: 'GET'
  expect-failure:
    description: Expect the check to fail (e.g. 4XX, 5XX status code)
    required: false
    default: 'false'
  max-attempts:
    description: Number of unsuccessful attempts to call URL before giving up
    required: false
    default: '1'
  retry-delay:
    description: Time between attempts (e.g. 3s, 1m)
    required: false
    default: '3s'
  follow-redirect:
    description: Follow redirected location in case request resulted in 3XX status code
    required: false
    default: 'true'
  cookie:
    description: |
      String representation of cookie attached to health check request.
      Format: `Name=Value`
    required: false
    default: ''
  basic-auth:
    description: |
      Basic auth login password pair.
      Format: `login:password`
    required: false
    default: ''
  contains:
    description: |
      String that must be present in the body at the target URL.
    required: false
    default: ''
  contains-not:
    description: |
      String that must not be present in the body at the target URL.
    required: false
    default: ''
  exponential-backoff:
    description: Retry with exponential backoff (true) or at regular intervals (false).
    required: false
    default: 'false'
branding:
  icon: alert-triangle
  color: yellow
runs:
  using: 'node20'
  main: 'dist/index.js'
