name: Verify action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-single-no-redirect:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: Check single, no redirect
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          url: https://postman-echo.com/status/200

  check-multiple-no-redirect:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: Check multiple, no redirect
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          url: https://postman-echo.com/status/200|https://postman-echo.com/status/304
          expect-failure: true # This is expected to fail as one of the URLs returns 304

  check-single-with-redirect:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: Check single, with redirect
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          url: https://postman-echo.com/status/200
          follow-redirect: true

  check-single-with-retry:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: Check single, with retry
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          url: https://postman-echo.com/status/200
          max-attempts: 5
          retry-delay: 2s

  check-single-retry-all:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: Check single, with retry-all
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          url: https://postman-echo.com/status/200
          max-attempts: 5
          retry-delay: 2s
          retry-all: true

  check-single-with-basic-auth:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: Check single, with basic auth
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          url: https://postman-echo.com/basic-auth
          basic-auth: 'postman:password'

  check-single-contains-no-redirect:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: Check single, no redirect, with contains
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          url: https://postman-echo.com/status/200
          contains: '"status": 200'

  check-single-not-contains-no-redirect:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: Check single, no redirect, with contains NOT
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          url: https://postman-echo.com/status/200
          not-contains: '"status": 200'

  expect-failure-on-500:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: Should fail when a 500 is encountered
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          url: https://postman-echo.com/status/500
          expect-failure: true
          max-attempts: 3

  expect-failure-on-400:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: Should fail when a 400 is encountered
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          url: https://postman-echo.com/status/400
          expect-failure: true
          max-attempts: 3
