name: Verify action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-single-no-redirect:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: Check single, no redirect
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          url: https://cypress.io
