name: Verify action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-local-success:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - name: Test
        run: |
          npm install
          npm run dev

  check-expect-success:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          url: https://cypress.io

  check-expect-failure:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          url: https://www.google.com
          expect-failure: true
